/**
 * Roadmap Updater — automatically updates ROADMAP.md in each repo
 * after task dispatch cycles.
 *
 * Responsibilities:
 *   1. Read current ROADMAP.md from the repo
 *   2. Mark dispatched tasks as completed/failed
 *   3. Append new items discovered during execution
 *   4. Commit the updated ROADMAP.md directly to main
 *   5. Log the update to memory store
 *
 * This closes the recursion loop: the agent reads the roadmap,
 * generates tasks, dispatches them, then updates the roadmap
 * with results — so the next cycle sees accurate state.
 */

import { githubTool } from "./tools/github.js";
import { getAgentState, type RoadmapItem, type GeneratedTask } from "./agent.js";
import { getLastDispatch, type DispatchResult } from "./task-dispatcher.js";
import { memoryStore } from "./memory/store.js";
import { broadcast } from "./events.js";

// ── Types ──

export type RoadmapUpdate = {
  repo: string;
  updated: boolean;
  itemsMarkedDone: string[];
  itemsMarkedFailed: string[];
  newSections: string[];
  commitSha?: string;
  error?: string;
};

// ── Helpers ──

function todayISO(): string {
  return new Date().toISOString().slice(0, 10);
}

/**
 * Parse a markdown roadmap into sections.
 * Each section starts with a heading (# or ##) or a list item with a checkbox.
 */
function findCheckboxLine(lines: string[], taskTitle: string): number {
  const normalizedTitle = taskTitle.toLowerCase().replace(/[^a-z0-9]/g, "");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    // Match unchecked checkbox items: - [ ] Some Title
    if (/^\s*-\s*\[[ ]\]/.test(line)) {
      const lineNorm = line.toLowerCase().replace(/[^a-z0-9]/g, "");
      // Fuzzy match: the roadmap item title should be substantially contained in the line
      if (lineNorm.includes(normalizedTitle) || normalizedTitle.includes(lineNorm.replace(/[^a-z0-9]/g, "").slice(0, 20))) {
        return i;
      }
    }
  }
  return -1;
}

function markCheckboxDone(line: string): string {
  return line.replace(/^(\s*-\s*)\[[ ]\]/, "$1[x]");
}

/**
 * Build a status summary section to append to the roadmap.
 */
function buildStatusSection(
  dispatch: DispatchResult,
  roadmapItems: RoadmapItem[],
): string {
  const lines: string[] = [];
  lines.push("");
  lines.push(`## Auto-Update: ${todayISO()}`);
  lines.push("");
  lines.push(`> Generated by local-devops-ai agent loop`);
  lines.push("");

  // Succeeded tasks
  const succeeded = dispatch.results.filter((r) => r.status === "success" || r.status === "dry-run");
  if (succeeded.length) {
    lines.push("### Completed");
    lines.push("");
    for (const r of succeeded) {
      const suffix = r.status === "dry-run" ? " *(dry-run)*" : "";
      const files = r.result?.filesChanged?.join(", ") ?? "";
      lines.push(`- [x] **${r.title}**${suffix}${files ? ` — files: ${files}` : ""}`);
    }
    lines.push("");
  }

  // Failed tasks
  const failed = dispatch.results.filter((r) => r.status === "failed");
  if (failed.length) {
    lines.push("### Needs Attention");
    lines.push("");
    for (const r of failed) {
      lines.push(`- [ ] **${r.title}** — ${r.reason ?? "unknown error"}`);
    }
    lines.push("");
  }

  // Skipped tasks
  const skipped = dispatch.results.filter((r) => r.status === "skipped");
  if (skipped.length) {
    lines.push("### Deferred");
    lines.push("");
    for (const r of skipped) {
      lines.push(`- [ ] **${r.title}** — ${r.reason ?? "skipped"}`);
    }
    lines.push("");
  }

  // Stats
  lines.push(`**Stats:** ${dispatch.dispatched} dispatched, ${dispatch.succeeded} succeeded, ${dispatch.failed} failed, ${dispatch.skipped} skipped (${dispatch.durationMs}ms)`);
  lines.push("");

  return lines.join("\n");
}

// ── Core Update Logic ──

/**
 * Update ROADMAP.md for a single repo based on dispatch results.
 */
async function updateRepoRoadmap(
  owner: string,
  repo: string,
  dispatch: DispatchResult,
  roadmapItems: RoadmapItem[],
): Promise<RoadmapUpdate> {
  const repoLabel = `${owner}/${repo}`;
  const result: RoadmapUpdate = {
    repo: repoLabel,
    updated: false,
    itemsMarkedDone: [],
    itemsMarkedFailed: [],
    newSections: [],
  };

  try {
    // 1. Read current ROADMAP.md
    let roadmapContent = "";
    let roadmapSha: string | undefined;
    let roadmapPath = "ROADMAP.md";

    for (const tryPath of ["ROADMAP.md", "roadmap.md", "docs/ROADMAP.md"]) {
      try {
        const file = await githubTool.getFile(owner, repo, tryPath);
        roadmapContent = file.content;
        roadmapSha = file.sha;
        roadmapPath = tryPath;
        break;
      } catch { continue; }
    }

    if (!roadmapContent) {
      result.error = "No ROADMAP.md found";
      return result;
    }

    // 2. Parse into lines and update checkboxes for completed tasks
    const lines = roadmapContent.split("\n");
    let modified = false;

    // Get tasks that belong to this repo
    const repoItems = roadmapItems.filter((item) => item.repo === repoLabel);
    const completedTaskIds = new Set(
      dispatch.results
        .filter((r) => r.status === "success" || r.status === "dry-run")
        .map((r) => r.taskId)
    );

    for (const item of repoItems) {
      // Check if ALL tasks for this item are complete
      const allTasksComplete = item.tasks.length > 0 &&
        item.tasks.every((t) => completedTaskIds.has(t.id));

      if (allTasksComplete) {
        const lineIdx = findCheckboxLine(lines, item.title);
        if (lineIdx >= 0) {
          lines[lineIdx] = markCheckboxDone(lines[lineIdx]);
          result.itemsMarkedDone.push(item.title);
          modified = true;
        }
      }
    }

    // 3. Append status section with dispatch results
    const statusSection = buildStatusSection(dispatch, roadmapItems);
    const updatedContent = lines.join("\n") + statusSection;
    modified = true; // always append status

    if (!modified) {
      return result;
    }

    // 4. Commit updated ROADMAP.md directly to main
    console.log(`[roadmap-updater] committing update to ${repoLabel}/${roadmapPath}`);
    const commitResult = await githubTool.commitFile(
      owner, repo, "main", roadmapPath,
      updatedContent,
      `chore(roadmap): auto-update after dispatch — ${dispatch.succeeded} succeeded, ${dispatch.failed} failed`,
      roadmapSha,
    );

    result.updated = true;
    result.commitSha = commitResult.sha;
    result.newSections.push("dispatch-status");

    return result;
  } catch (err) {
    result.error = (err as Error).message;
    return result;
  }
}

// ── Public API ──

/**
 * Update all repo roadmaps after a dispatch cycle.
 * Called automatically at the end of the agent loop's phase 3.
 */
export async function updateRoadmaps(): Promise<RoadmapUpdate[]> {
  const dispatch = getLastDispatch();
  if (!dispatch || dispatch.dispatched === 0) {
    console.log("[roadmap-updater] no dispatch results to report");
    return [];
  }

  const agentState = getAgentState();
  const results: RoadmapUpdate[] = [];

  // Group by repo
  const repos = new Set(agentState.roadmapItems.map((item) => item.repo));

  for (const repoLabel of repos) {
    const [owner, repo] = repoLabel.split("/");
    if (!owner || !repo) continue;

    console.log(`[roadmap-updater] updating ${repoLabel}...`);
    broadcast("roadmap-updater:start", { repo: repoLabel });

    const update = await updateRepoRoadmap(owner, repo, dispatch, agentState.roadmapItems);
    results.push(update);

    if (update.updated) {
      console.log(
        `[roadmap-updater] ${repoLabel}: ${update.itemsMarkedDone.length} items marked done, ` +
        `commit: ${update.commitSha?.slice(0, 7) ?? "none"}`
      );
    } else if (update.error) {
      console.warn(`[roadmap-updater] ${repoLabel}: ${update.error}`);
    }

    broadcast("roadmap-updater:complete", { repo: repoLabel, updated: update.updated });
  }

  // Log to memory
  const summary = results
    .map((r) => `${r.repo}: ${r.updated ? `updated (${r.itemsMarkedDone.length} done)` : r.error ?? "no changes"}`)
    .join("\n");

  await memoryStore.add({
    title: `Roadmap Update: ${results.filter((r) => r.updated).length}/${results.length} repos updated`,
    details: summary,
    tags: ["roadmap-updater", "auto"],
    source: "roadmap-updater",
  }).catch(() => {});

  return results;
}
